version: '3'

services:
  omdb:
    build:
      context: .
    volumes:
      - ./omdb:/src/omdb_root/omdb
    networks:
      - nginx_network
      - postgres
    depends_on:
      - postgres
    env_file:
      - config/omdb/ombd_dev_env
  nginx:
    image: nginx:latest
    ports:
      - '7000:80'
    volumes:
      - ./config/nginx/dev_conf.d:/etc/nginx/conf.d
    depends_on:
      - omdb
    networks:
      - nginx_network

  postgres:
    image: postgres:11
    env_file:
      - config/db/db_env
    networks:
      - postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres_db_volume: