version: '3.8'


services:
  omdb:
    image: omdb
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn omdb.wsgi:application --bind 0.0.0.0:7000
    expose:
      - 7000
    env_file:
      - config/omdb/ombd_dev_env
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
  nginx:
    image: nginx:latest
    ports:
      - '1337:80'
    volumes:
      - ./config/nginx/dev_conf.d:/etc/nginx/conf.d
    depends_on:
      - omdb

volumes:
  postgres_data:

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt