# Generated by Django 4.1.6 on 2023-02-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_episode_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='imdbRating',
            new_name='imdb_rating',
        ),
    ]
